name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t myapp .

    # Run Container
    - name: Run Container
      run: |
        docker run -d -p 3000:3000 --name mycontainer myapp

    # Check Running Containers
    - name: Verify Container
      run: docker ps

    # Test Application (optional)
    - name: Test App
      run: |
        curl http://localhost:3000 || echo "App not responding"
